version: '3'
services:
  web:
    build: .
    ports:
     - "8000:80"
    depends_on: [database, redis, mail]
    volumes:
      - .:/var/www/html
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD:
    ports:
      - "5432:5432"
    volumes:
      - ./devops/var/lib/postgresql:/var/lib/postgresql/data
  redis:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./devops/redis:/data
  mail:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
